### ISSUE TITLE
[Question] How to sell on waxpeer?

### ISSUE THREAD

**Issue by OceanManOne** [skylight-ity/waxpeer#23]
As the title says, I can't really find an API or a function just to list my items to sell on waxpeer.
I see a lot of options to buy but not for sell.

Any help or code examples would be appreciated

**Comment by skylight-ity** [comment]
@OceanManOne [Here](https://waxpeer.com/profile/user) you can get the API key and there are functions that enable you to fetch inventory and list the items on sale
