### ISSUE TITLE
Default value of a parameter "game" in "getMyInventory", should be "730" instead of "csgo"

### ISSUE THREAD

**Issue by SenTisso** [skylight-ity/waxpeer#5]
The title basically says it all. According to the documentation [api.waxpeer.com/docs/](https://api.waxpeer.com/docs/#/Steam/get_get_my_inventory), the value should be a number and even a default value in the documentation is `730`.

```
/**
 *
 * @param skip Skip items
 * @param game Game
 */
getMyInventory(skip = 0, game = 'csgo') { // here should be 'game = 730'
    return this.get('get-my-inventory', 'v1', `game=${game}&skip=${skip}`);
}
```

**Comment by SenTisso** [comment]
Created a pull request #6

**Comment by skylight-ity** [comment]
Fixed in the new update
